# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    aliases:
      - list
      - ls

  build:
    desc: Build the tash application
    cmds:
      - go build -o tash ./cmd/tash
    sources:
      - cmd/tash/**/*.go
      - internal/**/*.go
      - go.mod
      - go.sum
    generates:
      - tash

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test:verbose:
    desc: Run all tests with verbose output
    cmds:
      - go test -v ./...

  run:
    desc: Build and run the tash application
    deps: [build]
    cmds:
      - ./tash

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f tash

  lint:
    desc: Run linters
    cmds:
      - go vet ./...
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint run
        else
          echo "golangci-lint not installed, skipping additional linting"
        fi

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  tidy:
    desc: Tidy and verify go.mod
    cmds:
      - go mod tidy
      - go mod verify

  all:
    desc: Run all checks, tests, and build
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: build