# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  default:
    cmd: task --list-all
    summary: List all the available tasks
    desc: List all
    aliases:
      - list
      - ls

  ls:
    cmd: ls
    summary: List all files in current directory
    platforms:
      - linux
      
  dir:
    cmd: dir
    summary: List all files in current directory
    platforms:
      - windows
